/**
 * Exact static inventory for ChatGPT macOS 26.825.51511 (build 7377).
 *
 * These names describe the inspected host build. They are evidence for an
 * adapter and are not the stable extension API.
 */

export interface ObservedBuildIdentity {
  readonly appVersion: "26.825.51511";
  readonly appBuild: "7377";
  readonly electronVersion: "42.3.0";
  readonly chromiumVersion: "151.0.7922.174";
  readonly nodeVersion: "24.14.0";
  readonly nodeModuleAbi: "143";
  readonly nodeApiVersion: "10";
  readonly objcJsVersion: "1.5.0";
  readonly architecture: "arm64";
  readonly nodeOptionsEnabled: true;
  readonly rendererContextIsolation: true;
  readonly rendererNodeIntegration: false;
  readonly appAsarSha256: "f56ac8d5254a10fc4a04e7417fa787d135c3bbca49bad7d668d4ae65833d40c7";
  readonly packageJsonSha256: "9e3631c62571bbc844e7f1459ffe1e5b6c7204649402c739a653d50d6bafaf85";
  readonly preloadSha256: "6418d42c99961587e70f644f9757e7a2c124b4bf09a39ed75ca11a7dedffdc49";
  readonly mainBundleSha256: "bdb50b30baa121e89b8ae12347647a1d0380e6f6b1548a5e626b02f2ea843da0";
  readonly browserPagePreloadSha256: "326403c712d6a2e5bef388e277a8ace34c154fbadc477bc2eecf2a6e5015536f";
  readonly rendererBundleSha256: "ee33f32cc0b147ddc45e02f7a699eda98e7058dc16e67ee0dbfb5666e621a0bd";
}

export interface ObservedGetAccountTokenUsageParams {
  /** Read estimated usage for this thread instead of account-wide activity. */
  readonly threadId?: string | null;
}

export interface ObservedAccountTokenUsageSummary {
  readonly lifetimeTokens: bigint | null;
  readonly peakDailyTokens: bigint | null;
  readonly longestRunningTurnSec: bigint | null;
  readonly currentStreakDays: bigint | null;
  readonly longestStreakDays: bigint | null;
}

export interface ObservedAccountTokenUsageDailyBucket {
  readonly startDate: string;
  readonly tokens: bigint;
}

export interface ObservedThreadUsageBreakdownGroup {
  readonly model: string | null;
  readonly reasoningEffort: string | null;
  readonly speed: string | null;
  readonly estimatedUsageCreditsMicros: bigint;
  readonly netNewInputTokens: bigint | null;
  readonly cachedInputTokens: bigint | null;
  readonly inputTokens: bigint | null;
  readonly outputTokens: bigint | null;
  readonly totalTokens: bigint | null;
}

export interface ObservedThreadUsage {
  readonly threadId: string;
  readonly estimatedUsageCreditsMicros: bigint;
  readonly estimatedUsageUsdMicros: bigint | null;
  readonly groups: readonly ObservedThreadUsageBreakdownGroup[];
}

export interface ObservedGetAccountTokenUsageResponse {
  readonly summary: ObservedAccountTokenUsageSummary;
  readonly dailyUsageBuckets:
    | readonly ObservedAccountTokenUsageDailyBucket[]
    | null;
  readonly threadUsage?: ObservedThreadUsage | null;
}

export type ObservedPreloadBridgeMethod =
  | "acknowledgeChunkedMessage"
  | "getAppSessionId"
  | "getBuildFlavor"
  | "getDesktopUserAgent"
  | "getFastModeRolloutMetrics"
  | "getInitialSidebarBootstrap"
  | "getPathForFile"
  | "getPreloadStartedAtMs"
  | "getSentryInitOptions"
  | "getSharedObjectSnapshotValue"
  | "getSystemThemeVariant"
  | "isDeviceCheckSupported"
  | "isIntelMacBuild"
  | "sendMessageFromView"
  | "sendWorkerMessageFromView"
  | "showContextMenu"
  | "startFileDrag"
  | "subscribeToSystemThemeVariant"
  | "subscribeToWorkerMessages"
  | "triggerSentryTestError"
  | "windowType";

export type ObservedAppHostService =
  | "ambientSuggestions"
  | "appActions"
  | "appInfo"
  | "appUpdates"
  | "applicationMenu"
  | "appshot"
  | "artifactDocuments"
  | "avatarOverlay"
  | "browserAutocomplete"
  | "browserHost"
  | "browserPluginConfig"
  | "browserProfileImport"
  | "browserTabs"
  | "browserUsePermissions"
  | "browsingHistory"
  | "chatGptProjectFiles"
  | "chromeNativeHost"
  | "chromiumBrowser"
  | "chronicle"
  | "clientCoordination"
  | "clipboard"
  | "codexMicro"
  | "computerUseSettings"
  | "conversationalOnboarding"
  | "customAvatars"
  | "customRuntime"
  | "debug"
  | "demoTools"
  | "dictationAudio"
  | "dictationHistory"
  | "downloads"
  | "dynamicToolCalls"
  | "fileAttachments"
  | "fileDrags"
  | "github"
  | "hotkeyWindowCommands"
  | "hotkeyWindowHotkeys"
  | "httpFetch"
  | "inAppBrowserIncompleteNavigation"
  | "installerAttribution"
  | "keyboardModifiers"
  | "libraryFiles"
  | "localAutomationsScheduler"
  | "localEnvironments"
  | "localThreadCatalog"
  | "lsp"
  | "notificationPermissionsSupported"
  | "notifications"
  | "openIn"
  | "owlBrowserCrashCounter"
  | "owlFeatures"
  | "performanceTelemetry"
  | "pinnedThreads"
  | "pluginScheduledTasks"
  | "primaryRuntime"
  | "processMemory"
  | "projectlessWorkspace"
  | "projects"
  | "pullRequestMessageGeneration"
  | "quickChatWindow"
  | "realtimeContinuity"
  | "realtimeMemory"
  | "realtimeVoice"
  | "realtimeVoiceHistory"
  | "realtimeVoiceMultiAgentActivity"
  | "realtimeVoicePresentation"
  | "realtimeVoiceRuntime"
  | "remoteControlEnvironments"
  | "remoteHostedPIP"
  | "requestUserInputAutoResolution"
  | "startup"
  | "systemFonts"
  | "systemPermissions"
  | "terminal"
  | "threadArchive"
  | "threadMetadataGeneration"
  | "threadProjectAssignments"
  | "threadTurnSummaries"
  | "tracing"
  | "triggers"
  | "visualizations"
  | "windowNavigation"
  | "workspaceFiles";

/** Methods present in the renderer method-to-domain registry `mFi`. */
export type ObservedMethodDomainRegistryMethod =
  | "account/login/cancel"
  | "account/login/start"
  | "account/logout"
  | "account/rateLimitResetCredit/consume"
  | "account/rateLimits/read"
  | "account/read"
  | "account/usage/read"
  | "app/installed"
  | "app/list"
  | "app/read"
  | "collaborationMode/list"
  | "command/exec"
  | "config/batchWrite"
  | "config/mcpServer/reload"
  | "config/read"
  | "config/value/write"
  | "configRequirements/read"
  | "experimentalFeature/enablement/set"
  | "experimentalFeature/list"
  | "externalAgentConfig/detect"
  | "externalAgentConfig/import"
  | "externalAgentConfig/import/readHistories"
  | "feedback/upload"
  | "fs/copy"
  | "fs/createDirectory"
  | "fs/getMetadata"
  | "fs/readDirectory"
  | "fs/readFile"
  | "fs/remove"
  | "fs/unwatch"
  | "fs/watch"
  | "fs/writeFile"
  | "fuzzyFileSearch/sessionStart"
  | "fuzzyFileSearch/sessionStop"
  | "fuzzyFileSearch/sessionUpdate"
  | "hooks/list"
  | "interactive/liveSessions/list"
  | "interactive/session/upload"
  | "interactive/sessionSandbox/list"
  | "interactive/sessionSandbox/read"
  | "marketplace/add"
  | "marketplace/remove"
  | "marketplace/upgrade"
  | "mcpServer/event/stream/start"
  | "mcpServer/event/stream/stop"
  | "mcpServer/oauth/login"
  | "mcpServer/resource/read"
  | "mcpServer/tool/call"
  | "mcpServerStatus/list"
  | "memory/reset"
  | "mock/experimentalMethod"
  | "model/list"
  | "modelProvider/capabilities/read"
  | "permissionProfile/list"
  | "plugin/install"
  | "plugin/installed"
  | "plugin/list"
  | "plugin/read"
  | "plugin/search"
  | "plugin/share/delete"
  | "plugin/share/list"
  | "plugin/share/save"
  | "plugin/share/updateTargets"
  | "plugin/skill/read"
  | "plugin/uninstall"
  | "process/kill"
  | "process/resizePty"
  | "process/spawn"
  | "process/writeStdin"
  | "project/create"
  | "project/delete"
  | "project/import"
  | "project/list"
  | "project/move"
  | "project/read"
  | "project/update"
  | "remoteControl/client/list"
  | "remoteControl/client/revoke"
  | "remoteControl/disable"
  | "remoteControl/enable"
  | "remoteControl/pairing/start"
  | "remoteControl/pairing/status"
  | "remoteControl/status/read"
  | "review/start"
  | "skills/config/write"
  | "skills/extraRoots/set"
  | "skills/list"
  | "thread/approveGuardianDeniedAction"
  | "thread/archive"
  | "thread/backgroundTerminals/clean"
  | "thread/compact/start"
  | "thread/delete"
  | "thread/fork"
  | "thread/goal/clear"
  | "thread/goal/get"
  | "thread/goal/set"
  | "thread/inject_items"
  | "thread/items/list"
  | "thread/list"
  | "thread/loaded/list"
  | "thread/memoryMode/set"
  | "thread/metadata/update"
  | "thread/name/set"
  | "thread/read"
  | "thread/resume"
  | "thread/revert"
  | "thread/rollback"
  | "thread/search"
  | "thread/searchOccurrences"
  | "thread/section/move"
  | "thread/settings/update"
  | "thread/shellCommand"
  | "thread/start"
  | "thread/startAeon"
  | "thread/stop"
  | "thread/turns/list"
  | "thread/unarchive"
  | "thread/unsubscribe"
  | "threadSection/create"
  | "threadSection/delete"
  | "threadSection/list"
  | "threadSection/update"
  | "turn/interrupt"
  | "turn/start"
  | "turn/steer"
  | "windowsSandbox/readiness"
  | "windowsSandbox/setupStart";

export type ObservedAppServerNotification =
  | "account/login/completed"
  | "account/rateLimits/updated"
  | "account/updated"
  | "app/list/updated"
  | "authStatusChange"
  | "autoApprovalReview/strictReviewRequired"
  | "codex/event/agent_message"
  | "codex/event/agent_message_content_delta"
  | "codex/event/agent_message_delta"
  | "codex/event/agent_reasoning"
  | "codex/event/agent_reasoning_delta"
  | "codex/event/agent_reasoning_raw_content"
  | "codex/event/agent_reasoning_raw_content_delta"
  | "codex/event/agent_reasoning_section_break"
  | "codex/event/apply_patch_approval_request"
  | "codex/event/background_event"
  | "codex/event/collab_agent_interaction_begin"
  | "codex/event/collab_agent_interaction_end"
  | "codex/event/collab_agent_spawn_begin"
  | "codex/event/collab_agent_spawn_end"
  | "codex/event/collab_close_begin"
  | "codex/event/collab_close_end"
  | "codex/event/collab_resume_begin"
  | "codex/event/collab_resume_end"
  | "codex/event/collab_waiting_begin"
  | "codex/event/collab_waiting_end"
  | "codex/event/deprecation_notice"
  | "codex/event/dynamic_tool_call_request"
  | "codex/event/elicitation_request"
  | "codex/event/entered_review_mode"
  | "codex/event/error"
  | "codex/event/exec_approval_request"
  | "codex/event/exec_command_begin"
  | "codex/event/exec_command_end"
  | "codex/event/exec_command_output_delta"
  | "codex/event/exited_review_mode"
  | "codex/event/get_history_entry_response"
  | "codex/event/item_completed"
  | "codex/event/item_started"
  | "codex/event/list_custom_prompts_response"
  | "codex/event/list_remote_skills_response"
  | "codex/event/list_skills_response"
  | "codex/event/mcp_list_tools_response"
  | "codex/event/mcp_startup_complete"
  | "codex/event/mcp_startup_update"
  | "codex/event/mcp_tool_call_begin"
  | "codex/event/mcp_tool_call_end"
  | "codex/event/patch_apply_begin"
  | "codex/event/patch_apply_end"
  | "codex/event/plan_delta"
  | "codex/event/plan_update"
  | "codex/event/raw_response_item"
  | "codex/event/reasoning_content_delta"
  | "codex/event/reasoning_raw_content_delta"
  | "codex/event/remote_skill_downloaded"
  | "codex/event/remote_task_created"
  | "codex/event/request_user_input"
  | "codex/event/session_configured"
  | "codex/event/shutdown_complete"
  | "codex/event/stream_error"
  | "codex/event/task_complete"
  | "codex/event/task_started"
  | "codex/event/terminal_interaction"
  | "codex/event/thread_name_updated"
  | "codex/event/thread_rolled_back"
  | "codex/event/token_count"
  | "codex/event/turn_aborted"
  | "codex/event/turn_diff"
  | "codex/event/undo_completed"
  | "codex/event/undo_started"
  | "codex/event/user_message"
  | "codex/event/view_image_tool_call"
  | "codex/event/warning"
  | "codex/event/web_search_begin"
  | "codex/event/web_search_end"
  | "command/exec/outputDelta"
  | "configWarning"
  | "deprecationNotice"
  | "externalAgentConfig/import/completed"
  | "externalAgentConfig/import/progress"
  | "fs/changed"
  | "fuzzyFileSearch/sessionCompleted"
  | "fuzzyFileSearch/sessionUpdated"
  | "guardianWarning"
  | "hook/completed"
  | "hook/started"
  | "item/agentMessage/delta"
  | "item/autoApprovalReview/completed"
  | "item/autoApprovalReview/started"
  | "item/commandExecution/outputDelta"
  | "item/commandExecution/terminalInteraction"
  | "item/completed"
  | "item/fileChange/outputDelta"
  | "item/fileChange/patchUpdated"
  | "item/mcpToolCall/progress"
  | "item/plan/delta"
  | "item/reasoning/summaryPartAdded"
  | "item/reasoning/summaryTextDelta"
  | "item/reasoning/textDelta"
  | "item/started"
  | "loginChatGptComplete"
  | "mcpServer/event/stream/notification"
  | "mcpServer/oauthLogin/completed"
  | "mcpServer/startupStatus/updated"
  | "model/rerouted"
  | "model/safetyBuffering/updated"
  | "model/verification"
  | "process/exited"
  | "process/outputDelta"
  | "project/changed"
  | "rawResponse/completed"
  | "rawResponseItem/completed"
  | "remoteControl/status/changed"
  | "serverRequest/resolved"
  | "sessionConfigured"
  | "skills/changed"
  | "thread/archived"
  | "thread/closed"
  | "thread/compacted"
  | "thread/deleted"
  | "thread/environment/connected"
  | "thread/environment/disconnected"
  | "thread/goal/cleared"
  | "thread/goal/updated"
  | "thread/name/updated"
  | "thread/project/updated"
  | "thread/queue/changed"
  | "thread/realtime/closed"
  | "thread/realtime/error"
  | "thread/realtime/item/completed"
  | "thread/realtime/item/started"
  | "thread/realtime/item/transcript/delta"
  | "thread/realtime/itemAdded"
  | "thread/realtime/outputAudio/delta"
  | "thread/realtime/sdp"
  | "thread/realtime/started"
  | "thread/realtime/transcript/delta"
  | "thread/realtime/transcript/done"
  | "thread/reverted"
  | "thread/settings/updated"
  | "thread/started"
  | "thread/status/changed"
  | "thread/tokenUsage/updated"
  | "thread/unarchived"
  | "turn/completed"
  | "turn/diff/updated"
  | "turn/moderationMetadata"
  | "turn/plan/updated"
  | "turn/started"
  | "warning"
  | "windows/worldWritableWarning"
  | "windowsSandbox/setupCompleted";

export type ObservedChatGPTConversationClientMethod =
  | "attachProjectFiles"
  | "autoInstallEcosystemLauncher"
  | "bootstrapEcosystemLauncher"
  | "branch"
  | "callEcosystemMcp"
  | "cancelStream"
  | "conversationAttachmentDownloadLink"
  | "conversationAttachmentDownloadRequest"
  | "conversationAttachmentInfo"
  | "conversationFiles"
  | "createCompletionStreamHandlers"
  | "createFile"
  | "createLibraryDirectory"
  | "createPost"
  | "createProject"
  | "createShareLink"
  | "customAgentSystemHint"
  | "delete"
  | "deleteLibraryFile"
  | "deleteProject"
  | "deleteProjectFile"
  | "executeCodeBlockMagicEdit"
  | "executeMagicEditRequest"
  | "exportWritingBlock"
  | "fileDownloadLink"
  | "fileDownloadRequest"
  | "fileDownloadRequestFromDownloadUrl"
  | "fileInfo"
  | "finalizeFileUpload"
  | "generateConversationTitle"
  | "get"
  | "getBatch"
  | "getConversationStreamStatus"
  | "getConversationWebSocketUrl"
  | "getEcosystemWidget"
  | "getGizmo"
  | "getGizmoBootstrap"
  | "getLibraryDirectoryPath"
  | "getLibraryFileThumbnail"
  | "getProject"
  | "getSharedConversation"
  | "getSubagentThreadTurns"
  | "getWorkspaceSettings"
  | "getWritingBlockEmailConnectorLink"
  | "getWritingBlockEmailStatus"
  | "globalSearch"
  | "internalModels"
  | "isWritingBlockEmailConnectorSendEnabled"
  | "launchEcosystemWidget"
  | "list"
  | "listLibraryFiles"
  | "listLibraryNodes"
  | "listPinnedConversationItems"
  | "listPinnedGizmoItems"
  | "listPinnedProjectItems"
  | "listProjectConnectorScopes"
  | "listProjectConversations"
  | "listProjectSaves"
  | "listProjects"
  | "listRecentLibraryFiles"
  | "listVoices"
  | "listWritingBlockEmailConnectorLinks"
  | "markAnnouncementAsViewed"
  | "materializeMountedLibraryFile"
  | "modelConfig"
  | "models"
  | "optOutOfTrustedContactPrompts"
  | "patch"
  | "persistDilViewState"
  | "prepareCompletionStream"
  | "processFileUploadStream"
  | "refreshGenUiWidget"
  | "rename"
  | "renameProject"
  | "resumeCompletionStream"
  | "sandboxFileDownloadRequest"
  | "saveTemporaryConversation"
  | "search"
  | "searchLibraryFiles"
  | "searchWritingBlockEmailContacts"
  | "sendWritingBlockEmail"
  | "setAccountVoice"
  | "setArchived"
  | "setChatTheme"
  | "setGizmoPinned"
  | "setPinned"
  | "setProjectPinned"
  | "setUltraEffortEnabled"
  | "startCompletionStream"
  | "startSidebarConversationStream"
  | "steerCompletion"
  | "stopCompletion"
  | "submitCloudBrowserFormFill"
  | "submitCodeBlockFeedback"
  | "submitImplicitMessageFeedback"
  | "submitLearningBlockFeedback"
  | "submitWritingBlockFeedback"
  | "synthesizeConversationAudio"
  | "synthesizePronunciationAudio"
  | "systemHints"
  | "tppModels"
  | "unsendWritingBlockEmail"
  | "updateCodeBlock"
  | "updateLibraryFile"
  | "updateShareLink"
  | "updateWritingBlock"
  | "uploadFileBytes"
  | "userSettings";

export type ObservedCommandId =
  | "approval.approve"
  | "approval.decline"
  | "archiveThread"
  | "clearAllUnreads"
  | "codexMicroSettings"
  | "composer.addFiles"
  | "composer.addPhotos"
  | "composer.captureAppshot"
  | "composer.clear"
  | "composer.cycleReasoningEffort"
  | "composer.decreaseReasoningEffort"
  | "composer.increaseReasoningEffort"
  | "composer.openModelPicker"
  | "composer.openProjectPicker"
  | "composer.queue"
  | "composer.startDictation"
  | "composer.startVoiceMode"
  | "composer.steer"
  | "composer.submit"
  | "composer.submitInBackground"
  | "composer.toggleFastMode"
  | "composer.togglePlanMode"
  | "composer.toggleWorkRunLocation"
  | "composer.toggleWorktreeMode"
  | "copyConversationMarkdown"
  | "environmentAction1"
  | "environmentAction2"
  | "environmentAction3"
  | "environmentAction4"
  | "environmentAction5"
  | "environmentAction6"
  | "environmentAction7"
  | "environmentAction8"
  | "environmentAction9"
  | "feedback"
  | "file.goToDefinition"
  | "file.navigateBack"
  | "file.navigateForward"
  | "findInThread"
  | "focusBrowserAddressBar"
  | "focusMainChat"
  | "focusQuickChat"
  | "focusSideChat"
  | "forceReloadSkills"
  | "forkThread"
  | "git.commit"
  | "git.createBranch"
  | "git.createDraftPullRequest"
  | "git.createPullRequest"
  | "git.mergePullRequest"
  | "git.openPullRequest"
  | "git.toggleBlame"
  | "globalDictationHold"
  | "globalDictationToggle"
  | "goToLine"
  | "hotkeyWindow"
  | "importExternalAgent"
  | "keyboardShortcuts"
  | "logOut"
  | "manageTasks"
  | "markThreadUnread"
  | "mcpSettings"
  | "navigateBack"
  | "navigateBrowserBack"
  | "navigateBrowserForward"
  | "navigateForward"
  | "newProjectlessTask"
  | "newTask"
  | "nextRecentThread"
  | "nextTab"
  | "nextThread"
  | "nextThreadNeedingAttention"
  | "openAvatarOverlay"
  | "openBrowserTab"
  | "openControlWindow"
  | "openFolder"
  | "openReviewTab"
  | "openSideChat"
  | "openSkills"
  | "openThreadInNewWindow"
  | "personalitySettings"
  | "previousRecentThread"
  | "previousTab"
  | "previousThread"
  | "quickChat"
  | "realtimeVoice"
  | "realtimeVoice.endCall"
  | "realtimeVoice.toggleMicrophoneMute"
  | "realtimeVoice.toggleOutputMute"
  | "recentThread1"
  | "recentThread2"
  | "recentThread3"
  | "recentThread4"
  | "recentThread5"
  | "recentThread6"
  | "redoAppAction"
  | "reopenClosedTab"
  | "searchChats"
  | "settings"
  | "showKeyboardShortcuts"
  | "switchToMode1"
  | "switchToMode2"
  | "switchToMode3"
  | "temporaryChat"
  | "thread1"
  | "thread2"
  | "thread3"
  | "thread4"
  | "thread5"
  | "thread6"
  | "thread7"
  | "thread8"
  | "thread9"
  | "toggleBottomPanel"
  | "toggleBrowserPanel"
  | "toggleDebugModal"
  | "toggleMaximizeSidePanel"
  | "togglePinnedSummary"
  | "togglePriorityFilter"
  | "toggleReviewTab"
  | "toggleSidePanel"
  | "toggleSidebar"
  | "toggleTerminal"
  | "toggleThreadPin"
  | "undoAppAction";

export type ObservedSettingsSectionId =
  | "agent"
  | "appearance"
  | "appshots"
  | "browser-use"
  | "chronicle"
  | "cloud-environments"
  | "cloud-settings"
  | "code-review"
  | "debug"
  | "environments"
  | "general-settings"
  | "git-settings"
  | "hooks-settings"
  | "import"
  | "keyboard-shortcuts"
  | "local-environments"
  | "mcp-settings"
  | "personalization"
  | "plugins-settings"
  | "skills-settings"
  | "usage"
  | "voice"
  | "worktrees";

export type ObservedThreadSurfaceKind =
  | "thread"
  | "thread-summary"
  | "detail"
  | "browser"
  | "files"
  | "file-editor"
  | "review"
  | "terminal"
  | "side-chat"
  | "artifact"
  | "plan"
  | "goal"
  | "sources"
  | "subagents"
  | "automation"
  | "pull-request"
  | "mcp-app"
  | "mcp-extension"
  | "mcp-file"
  | "entity";

export type ObservedThreadTabPlacement = "right-panel" | "bottom-panel";
export type ObservedThreadWorkspaceMode = "full" | "split";
export type ObservedThreadContentSide = "left" | "right";

/** First-party direct UI mechanisms found in this exact renderer build. */
export type ObservedDirectUiMechanism =
  | "bottom-panel-controller"
  | "command-handler"
  | "command-menu-provider"
  | "composer-footer-controls"
  | "header-action"
  | "header-context-menu-item"
  | "home-announcement-entries"
  | "home-suggestion-items"
  | "native-notification"
  | "product-mode-menu"
  | "right-panel-controller"
  | "tab-type"
  | "toast";

export type ObservedHomeSuggestionLayout = "cards" | "list";
export type ObservedHomeSuggestionCategoryId =
  | "codex-explore"
  | "codex-create"
  | "codex-review"
  | "codex-fix";
export type ObservedHomeSuggestionItemField =
  | "description"
  | "disabled"
  | "icon"
  | "id"
  | "keyboardShortcut"
  | "label"
  | "listIcon"
  | "onClick"
  | "onDismiss"
  | "tooltipContent";

export type ObservedHomeAnnouncementEntryField =
  | "content"
  | "isEligible"
  | "isLoading";
export type ObservedHomeAnnouncementCardField =
  | "description"
  | "dismissAction"
  | "leadingVisual"
  | "primaryAction"
  | "title";

export type ObservedProductMode = "work" | "codex";
export type ObservedProductModeMenuItemId = "app.work" | "app.codex";
export type ObservedWorkModeAccess = "chatgpt" | "chatgpt_work" | "work";

export type ObservedComposerActionPlacement =
  | "composer.footer.leading"
  | "composer.footer.trailing"
  | "composer.action-bar.leading"
  | "composer.action-bar.trailing"
  | "composer.utility.leading"
  | "composer.utility.trailing";

export type ObservedToastServiceMethod =
  | "closeAll"
  | "custom"
  | "danger"
  | "info"
  | "success"
  | "warning";

export type ObservedToastOptionField =
  | "content"
  | "description"
  | "duration"
  | "errorAnalytics"
  | "hasCloseButton"
  | "id"
  | "leading"
  | "level"
  | "onRemove"
  | "position"
  | "primaryAction"
  | "secondaryAction"
  | "testId";

export type ObservedToastActionField = "label" | "loading" | "onClick";

export type ObservedDesktopNotificationServiceMethod = "hide" | "show";
export type ObservedDesktopNotificationKind =
  | "permission"
  | "question"
  | "turn-complete";
export type ObservedDesktopNotificationDescriptorField =
  | "actions"
  | "body"
  | "conversationId"
  | "hostId"
  | "id"
  | "kind"
  | "navigationPath"
  | "replyPlaceholder"
  | "requestId"
  | "title";
export type ObservedDesktopNotificationActionField =
  | "actionType"
  | "id"
  | "title";
export type ObservedDesktopNotificationResultField = "id" | "reply" | "type";
export type ObservedDesktopNotificationHideField =
  | "conversationId"
  | "navigationPath"
  | "notificationId";

export type ObservedBuilderOrSlotCompositionPoint =
  | "assistant-message.additional-actions"
  | "assistant-message.after"
  | "assistant-message.persistent-actions"
  | "assistant-selection.actions"
  | "bottom-panel.empty-state"
  | "bottom-panel.tabs.after"
  | "bottom-panel.tabs.after-sticky"
  | "composer.action-bar.leading"
  | "composer.action-bar.trailing"
  | "composer.attachments"
  | "composer.banners"
  | "composer.footer.leading"
  | "composer.footer.trailing"
  | "composer.utility.leading"
  | "composer.utility.trailing"
  | "home.announcements"
  | "home.new-chat-suggestions"
  | "profile.menu"
  | "right-panel.empty-state"
  | "right-panel.tabs.after"
  | "right-panel.tabs.after-sticky"
  | "right-panel.tabs.before"
  | "sidebar.destination.trailing"
  | "sidebar.destinations"
  | "sidebar.product-mode.menu"
  | "sidebar.thread-row.actions"
  | "sidebar.thread-row.indicator-hover"
  | "sidebar.thread-row.indicator-idle"
  | "sidebar.thread-row.indicator-rest"
  | "sidebar.thread-row.meta"
  | "sidebar.thread-row.menu"
  | "sidebar.thread-row.overlay-meta"
  | "sidebar.thread-row.priority-indicator"
  | "sidebar.thread-row.secondary"
  | "sidebar.thread-row.title-prefix"
  | "sidebar.thread-row.title-suffix"
  | "surface.new-tab"
  | "thread.header.menu"
  | "user-message.additional-actions";

/** No first-party registry or contribution prop was found for these areas. */
export type ObservedMissingCompositionRegistry =
  | "generic-transcript-item"
  | "global-banner"
  | "main-route"
  | "settings-section"
  | "sidebar-fixed-row"
  | "universal-context-menu";

export type ObservedSidebarDestinationId =
  | "builtin:archive"
  | "builtin:automations"
  | "builtin:debug"
  | "builtin:finance"
  | "builtin:library"
  | "builtin:projects"
  | "builtin:pull-requests"
  | "builtin:security"
  | "builtin:sites"
  | "builtin:skills"
  | `mcp:${string}`;

export type ObservedPanelDefinitionField =
  | "Component"
  | "defaultState"
  | "dropDestinations"
  | "durableRoute"
  | "getContextMenuItems"
  | "getIcon"
  | "getId"
  | "getTitle"
  | "isAvailable"
  | "kind";

export type ObservedThreadHeaderActionId =
  | "chatgpt-conversation-side-panel"
  | "chatgpt-temporary-chat"
  | "home-composer-mode-toggle"
  | "new-chat"
  | "sidebar-trigger"
  | "thread-side-panel-close"
  | "thread-side-panel-new-tab"
  | "unified-thread-actions"
  | "unified-workspace-layout-chooser"
  | `${string}-bottom-panel-toggle`
  | `${string}-panel-toggles`;
